hw4 add tasks in js
pyropetrick/js-practice-4 pull request #1
Opened 2022-07-26 20:09 UTC by pyropetrick

2022-07-28 10:04 UTC, igorstasiuk requested changes

2022-07-28 10:04 UTC, igorstasiuk commented on script/index.js
> +        for (let i = 0; i < amtPhones ;i++) {
тут цикл в цикле не надо

2022-07-28 12:15 UTC, pyropetrick commented on script/index.js
> +    let amountPhone = 2;
а это количество телефонов которые хочет купить

2022-08-25 12:04 UTC, igorstasiuk approved these changes

2022-08-25 12:04 UTC, merged